export const COLUMNS = [
  {
    id: 'Select All',
    key: 'id',
    additionalInfo: null,
    checked: true,
    bold: true,
    isSticky: true,
    component: 'checkbox',
    order: 0,
  },
  {
    id: 'Products',
    key: 'product',
    additionalInfo: '100g serving',
    checked: true,
    bold: false,
    isSticky: true,
    order: 1,
  },
  {
    id: 'Calories',
    key: 'calories',
    additionalInfo: null,
    checked: true,
    bold: false,
    isSticky: true,
    order: 2,
  },
  {
    id: 'Fat',
    key: 'fat',
    additionalInfo: 'g',
    checked: true,
    bold: false,
    isSticky: true,
    order: 3,
  },
  {
    id: 'Carbs',
    key: 'carbs',
    additionalInfo: 'g',
    checked: true,
    bold: false,
    isSticky: true,
    order: 4,
  },
  {
    id: 'Protein',
    key: 'protein',
    additionalInfo: 'g',
    checked: true,
    bold: false,
    isSticky: true,
    order: 5,
  },
  {
    id: 'Iron',
    key: 'iron',
    additionalInfo: '%',
    checked: true,
    bold: false,
    isSticky: true,
    order: 6,
  },
].filter(i => i);